### ISSUE TITLE
Mac build fail

### ISSUE THREAD

**Issue by cdeil** [libgamera/GAMERA#11]
I get this error when I try to compile Gamerapy:

```
$ make gamerapy
cd python;\
    swig -python -c++ -nosafecstrings -outdir ../lib -o _gamerapy.cc gamerapy.i;\
    python setup.py build_ext --build-lib ../lib;\
    cd ..;\

running build_ext
building '_gamerapy' extension
creating build
creating build/temp.macosx-10.11-x86_64-3.4
creating build/src
/usr/bin/clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c _gamerapy.cc -o build/temp.macosx-10.11-x86_64-3.4/_gamerapy.o -std=c++11 -L/opt/local/lib -lgsl -lgslcblas -lm
clang: warning: argument unused during compilation: '-L/opt/local/lib -lgsl -lgslcblas -lm'
In file included from _gamerapy.cc:3146:
./../include/Radiation.h:9:10: fatal error: 'gsl/gsl_sf_bessel.h' file not found
#include <gsl/gsl_sf_bessel.h>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

Somehow your `python/setup.py` is wrong, the linker flags are passed to the compile step:

```
$ cd python/
$ /usr/bin/clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c _gamerapy.cc -o build/temp.macosx-10.11-x86_64-3.4/_gamerapy.o -std=c++11 -L/opt/local/lib -lgsl -lgslcblas -lm
clang: warning: -lgsl: 'linker' input unused
clang: warning: -lgslcblas: 'linker' input unused
clang: warning: -lm: 'linker' input unused
clang: warning: argument unused during compilation: '-L/opt/local/lib'
In file included from _gamerapy.cc:3146:
./../include/Radiation.h:9:10: fatal error: 'gsl/gsl_sf_bessel.h' file not found
#include <gsl/gsl_sf_bessel.h>
         ^
1 error generated.
```

Looks like on travis-ci `gsl-config` isn't found:

```
gsl-config: Command not found
```

https://travis-ci.org/JoachimHahn/GAMERA/jobs/91447338#L2321
https://travis-ci.org/JoachimHahn/GAMERA/jobs/91447340#L2320
https://github.com/JoachimHahn/GAMERA/blob/master/.travis.yml#L11

I'm not a homebrew user, probably you'll have to add it's location to the PATH?
http://stackoverflow.com/questions/10343834/homebrew-wants-me-to-amend-my-path-no-clue-how

Let me know if you can't figure the setup.py stuff out, we could have a look tomorrow evening.

**Comment by JoachimHahn** [comment]
OK, I think it should be fixed now... I dropped pkgconfig in the setup.py for a direct system call via
the subprocess module of gsl-config.

Does it work on your system now?

**Comment by cdeil** [comment]
```
$ make gappa
cd python;\
    swig -python -c++ -nosafecstrings -outdir ../lib -o _gappa.cc gappa.i;\
    python setup.py build_ext --build-lib ../lib;\
    cd ..;\

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    GSL_LIBS = string.split(subprocess.check_output(['gsl-config','--libs']))
AttributeError: 'module' object has no attribute 'split'
```

Does it work on travis-ci?
I don't think it does on Python 3?

**Comment by JoachimHahn** [comment]
This worked on sever Apple machines... Removed this method of splitting up the string anyways and
replaced it by standard python syntax (i.e. "randomstring".split() ). 
The code now compiles on travis-ci !!

**Comment by cdeil** [comment]
No, it still doesn't work.
I've made a pull request (#14) that works for me on Python 3, and it should work the same on Python 2.
You should add a build on travis-ci that uses Python 3 though, i.e. extend your test matrix.
